### ISSUE TITLE
Wasm errors building bindings locally

### ISSUE THREAD

**Issue by galderz** [lightningdevkit/ldk-garbagecollected#1]
I've tried to build the bindings locally but I got some errors:

With `debug=true`:
```bash
❯ ./genbindings.sh /opt/matt-rust-lightning "-I/opt/java-11/include/ -I/opt/java-11/include/linux/" true false
Creating Java bindings...
Building Java bindings...
Creating TS bindings...
Building TS bindings...
clang-11: error: no such file or directory: '/opt/matt-rust-lightning/lightning-c-bindings/target/wasm32-wasi/debug/libldk.a'
```

With `debug=false`:
```
❯ ./genbindings.sh /opt/matt-rust-lightning "-I/opt/java-11/include/ -I/opt/java-11/include/linux/" true false
Creating Java bindings...
Building Java bindings...
Creating TS bindings...
Building TS bindings...
clang-11: error: no such file or directory: '/opt/matt-rust-lightning/lightning-c-bindings/target/wasm32-wasi/debug/libldk.a'
```

**Comment by TheBlueMatt** [comment]
Oops, right, I need to push the changes that also support building wasm rust binaries. A `cargo build --target=wasm32-wasi` in lightning-c-bindings should do it, but note that rust-lightning needs to depend on a newer version of rust-bitcoin (or pull the patch from  https://github.com/rust-bitcoin/rust-secp256k1/pull/242) and you need rustc nightly to get the new wasm32-wasi ABI (which matches clang's ABI).

**Comment by galderz** [comment]
Fair enough. TBH, I don't need wasm stuff right now. I didn't check it in detail, but it'd appear that in spite of the error, the Java bindings would be generated. They're the ones I'm looking to try out and the ones I'd like to make sure I can build locally in case I need to modify anything.

**Comment by TheBlueMatt** [comment]
Correct, the Java bindings should be generated fine in spite of the WASM build failures.

**Comment by TheBlueMatt** [comment]
This should now work with latest upstream as long as you use rustc nightly/beta.
