### ISSUE TITLE
PeerManager connection issue with TypeScript LDK-C-Bindings v0.0.106.1

### ISSUE THREAD

**Issue by gr0kchain** [lightningdevkit/ldk-garbagecollected#101]
Looking for some input on an issue I'm having around peer connections using the typescript bindings. I've gotten all the steps setup as per the tutorials, but on connecting to a node I receive the following logs from the peermanager.

```
var address = ldk.NetAddress.constructor_ipv4([127,0,0,1],9735);
peer_manager.new_outbound_connection(Buffer.from('0374f296fbe03d451d9bd182ae7fc797a2432b112717b029607b4e3c623a9282f9', 'hex'), socket, address);
```

I can see comms between the TS node and my remote Polar LND node, and imagine the handshake is happening as per the loggers output. 

Been trying to inspect the traffic between these, but can confirm the remote node is responding via a protocol analyser. Trying to get https://github.com/nayutaco/lightning-dissector working so I can inspect the network communication to identify the responses being receive from the LND node, but for now here's my code for connecting. 

```
lightning::ln::peer_handler: Finished noise handshake for connection with 0374f296fbe03d451d9bd182ae7fc797a2432b112717b029607b4e3c623a9282f9
lightning::ln::peer_handler: Enqueueing message Init { features: [170, 81, 2, 8, 0, 160], remote_network_address: Some(IPv4 { addr: [7, 38, 95, 94], port: 35745 }) } to 0374f296fbe03d451d9bd182ae7fc797a2432b112717b029607b4e3c623a9282f9
```

The tuple return by the remote server looks bizarre [7, 38, 95, 94] and from what I can see this is derived from the socket itself. After receiving these however peermanager.get_peer_node_ids() returns an empty array []. I am unable to use lightning-net-tokio (rust) or the NioPeer (java), so using a raw nodejs socket which is managed through the SockerDescriptor interface.

**Comment by gr0kchain** [comment]
FYI, I've also tried this against a locally configured lnd node to isolate wether or not this was related to docker but received the same result.

**Comment by TheBlueMatt** [comment]
Looks like that's not valid, tsc says:

```
test/tests.mts:250:53 - error TS2345: Argument of type 'number[]' is not assignable to parameter of type 'Uint8Array'.
  Type 'number[]' is missing the following properties from type 'Uint8Array': BYTES_PER_ELEMENT, buffer, byteLength, byteOffset, and 3 more.

250  const v4_netaddr = ldk.NetAddress.constructor_ipv4([127,0,0,1], 9735);
```

**Comment by TheBlueMatt** [comment]
Hmm, still, looks like it works just fine locally in the TS tests. I did fix some conversion issues in 0.0.108 with #104, though I don't think those should have caused this.

**Comment by TheBlueMatt** [comment]
Can you test 0.0.108.1 and let me know if its still visible there?

**Comment by gr0kchain** [comment]
I'm running through the steps required to build the bindings on this end but running into build errors. Could you please update the npm package [lightningdevkit](https://www.npmjs.com/package/lightningdevkit) in the meantime?

**Comment by TheBlueMatt** [comment]
I already had, but apparently npmjs takes like 6-12 hours to make things available.

**Comment by gr0kchain** [comment]
Thanks for extending the tests to include the SocketDescriptor and NetAddress. When updating the value [42, 0, 42, 1] to [127,0,0,1] however, I receive a different output to what is expected. 

Output for using 42.0.42.1
```
lightning::ln::peer_handler: Enqueueing message Init { features: [170, 81, 10, 8, 0, 160, 8], remote_network_address: Some(IPv4 { addr: [42, 0, 42, 1], port: 9735 }) } to 02888f2e3df341d21240f769afd83938fdc1878356769aae64141880d810c61dce
```

Output for 127.0.0.1
```
lightning::ln::peer_handler: Enqueueing message Init { features: [170, 81, 10, 8, 0, 160, 8], remote_network_address: None } to 02888f2e3df341d21240f769afd83938fdc1878356769aae64141880d810c61dce
```

This also varies from the initial response highlighted above. Not sure if this is an exception for the local loopback device perhaps not being considered "remote"?

**Comment by gr0kchain** [comment]
Also, I've upgraded to using the TS bindings using `LDK-Java Bindings with LDK v0.0.109-9-g7ffb50b4d93022d3 and LDK-C-Bindings v0.0.109.0`. 

The tests for the peermanager appear to be working fine. When however I execute this against an external peer I receive an error 

This is currently reproducible by the latest commit https://github.com/synonymdev/ldk-node-js/commit/49202aaa6025c393c1616879af9e5bb16cbc0f19 

```
RuntimeError: table index is out of bounds
    at wasm://wasm/00f37812:wasm-function[901]:0x5195e
    at wasm://wasm/00f37812:wasm-function[3924]:0x1a8e59
    at wasm://wasm/00f37812:wasm-function[3923]:0x1a8e4c
    at wasm://wasm/00f37812:wasm-function[5994]:0x25148c
    at MessageHandler_free (file:///Users/gr0kchain/projects/ldk/ldk-node-js/node_modules/lightningdevkit/bindings.mjs:24784:38)
    at file:///Users/gr0kchain/projects/ldk/ldk-node-js/node_modules/lightningdevkit/structs/CommonBase.mjs:5:9
    at freer (file:///Users/gr0kchain/projects/ldk/ldk-node-js/node_modules/lightningdevkit/structs/CommonBase.mjs:1:21)
    at FinalizationRegistry.cleanupSome (<anonymous>)
    ```

**Comment by TheBlueMatt** [comment]
> Output for 127.0.0.1

Yes, that is expected. We never send private addresses to our peers there.

**Comment by gr0kchain** [comment]
Multiple peers hosted on the same interface though?

**Comment by TheBlueMatt** [comment]
We don't do any interface checks or anything like that, we just check if the address is in the private address ranges (10., 192.168., 127., etc, etc).

**Comment by TheBlueMatt** [comment]
Right, your issue is a type confusion error. This diff seems to fix it (I'd strongly recommend doing an LDK implementation in TS, not JS, the errors you end up with in JS with type confusion are....confusing):

```
diff --git a/node.js b/node.js
index 7aa43c9..7e005e8 100644
--- a/node.js
+++ b/node.js
@@ -134,7 +134,7 @@ async function start_ldk(ldk) {
 
     let genesis_hash = await rpcclient("getblockhash",[0]);
     let network_graph = ldk.NetworkGraph.constructor_new(Buffer.from(genesis_hash, "hex"));
-    let net_graph_msg_handler = ldk.MessageHandler.constructor_new(network_graph, new ldk.Option_AccessZ(), logger) // removed in the new bindings
+    let net_graph_msg_handler = ldk.P2PGossipSync.constructor_new(network_graph, new ldk.Option_AccessZ(), logger) // removed in the new bindings
     // <E2><9C><85> Step 12: Initialize the PeerManager
 
     let lightning_msg_handler = ldk.MessageHandler.constructor_new({
```

**Comment by TheBlueMatt** [comment]
Closing this as I don't believe there's any more issues here. Lets move to a new issue as things crop up.
