### ISSUE TITLE
Batteries included for TypeScript bindings

### ISSUE THREAD

**Issue by gr0kchain** [lightningdevkit/ldk-garbagecollected#102]
Are the any intentions on creating the batteries helpers as seen for java for the TypeScript bindings? 

https://github.com/lightningdevkit/ldk-garbagecollected/tree/main/src/main/java/org/ldk/batteries

**Comment by TheBlueMatt** [comment]
In general, yes, though maybe only the TCP mapping. I kinda regret the ChannelManagerConstructor utility that is in the Java batteries - it's overly-opinionated but still tries to be flexible and kinda fails at both.

**Comment by TheBlueMatt** [comment]
We now have a node-specific TCP mapping, which is most of what we can do here. I think it'd be cool to also support websocket connections directly in LDK and then map to websockets here, but that's much further off, and ultimately requires a TLS proxy as well. Once we expose the KVStore (https://github.com/lightningdevkit/ldk-c-bindings/issues/90) I'm not sure what else is immediately doable here. Gonna close as completed even though there's some long-term ambitions, but we should open separate issues for that as things come up that would be helpful to you.
