### ISSUE TITLE
how to build LDK-release.aar?

### ISSUE THREAD

**Issue by ghbrylee** [lightningdevkit/ldk-garbagecollected#108]
Does anyone know how to build LDK-release.aar? LDK dev team uploaded LDK-relase.aar officially on Github. But there are no docs or guides about it. Would you please give me some advice?

<img width="236" alt="Screen Shot 2022-07-06 at 5 49 48 PM" src="https://user-images.githubusercontent.com/37205403/177510737-c344b67a-30d0-492d-9b51-a3102331c6c8.png">

**Comment by TheBlueMatt** [comment]
You're probably best off just doing what CI does - it currently tests that android binaries are deterministic so you should be able to generate identical binaries if you follow it - https://github.com/lightningdevkit/ldk-garbagecollected/blob/main/.github/workflows/build.yml#L254-L334
