### ISSUE TITLE
PathFailure Constructor

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/ldk-garbagecollected#131]
Looks like for some reason there isn't one.

**Comment by keyuebao** [comment]
@TheBlueMatt I think we're all good actually, there are `InitialSend` and  `OnPath` which can be used to construct an instance of this event: https://github.com/lightningdevkit/ldk-garbagecollected/blob/main/src/main/java/org/ldk/structs/PathFailure.java#L37-L73

Feel free to close this issue - thanks!
