### ISSUE TITLE
ChannelManagerConstructor doesn't accept PhantomKeyManager

### ISSUE THREAD

**Issue by keyuebao** [lightningdevkit/ldk-garbagecollected#132]
This happens in Java bindings, ChannelManager constructors only take in `KeysManager` right now but not `PhantomKeysManager` even though they are very very similar

**Comment by TheBlueMatt** [comment]
Not sure if it didn't at the time, but it definitely does now - it currently takes `EntropySource entropy_source, NodeSigner node_signer, SignerProvider signer_provider,` which can be constructed from any keys manager.
