### ISSUE TITLE
Incorrect String Conversion in JNI to C Bindings

### ISSUE THREAD

**Issue by zpv** [lightningdevkit/ldk-garbagecollected#136]
## What

Incorrect handling of string conversion between Java strings and C strings in the JNI bindings. The conversion does not correctly handle characters that are encoded into 4-bytes in UTF-8 (e.g. some emojis).

https://github.com/lightningdevkit/ldk-garbagecollected/blob/3e33cfde4213dafe90eb976eb67224e2451da855/java_strings.py#L465-L487

- Current conversion functions `GetStringUTFChars` and `NewStringUTF` expect Modified UTF-8 (MUTF-8) format and not regular UTF-8.

- Java's MUTF-8 to C's UTF-8 encoding is causing data corruption for certain UTF-8 characters.

## Possible Fix?

https://stackoverflow.com/a/32215302

> - Use GetStringChars() to get the original UTF-16 encoded characters, and then create your own UTF-8 byte array from that. The conversion from UTF-16 to UTF-8 is a very simply algorithm to implement by hand, or you can use any pre-existing implementation provided by your platform or 3rd party libraries.
> 
> - Have your JNI code call back into Java to invoke the [String.getBytes(String charsetName)](http://docs.oracle.com/javase/7/docs/api/java/lang/String.html#getBytes(java.lang.String)) method to encode the jstring object to a UTF-8 byte array, eg:

**Comment by TheBlueMatt** [comment]
I'm fine with either proposed solution, the second is easier to reason about but a chunk more code and criss-crossing different parts of the codebase, if the first solution is as simple as random stackoverflow commenters think that's probably simpler.
