### ISSUE TITLE
Update README to reflect status/nature of Java and TypeScript bindings support

### ISSUE THREAD

**Issue by moneyball** [lightningdevkit/ldk-garbagecollected#137]
TypeScript support says "alpha" but it is more mature than that.

Java says beta but Cash App has been in production for over 1.5 years. Not sure exactly what the right framing should be but we need to strike the right balance between scaring people away from using it in production (when clearly it can be used in production) but also setting expectations about what problems do exist or might exist.

**Comment by G8XSU** [comment]
Current status that needs to be reflected: 

"Java/Kotlin(Stable), Swift(Stable), TypeScript/JavaScript(Beta), C++(Alpha)"
We don't want to list C, because it's unusable.
