### ISSUE TITLE
Invalid invoice parsing issues

### ISSUE THREAD

**Issue by Synesso** [lightningdevkit/ldk-garbagecollected#41]
v0.0.99-2

Testing https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#examples-of-invalid-invoices

* Invalid sub-millisatoshi precision is parsed as valid.
```lnbc2500000001p1pvjluezpp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqdq5xysxxatsyp3k7enxv4jsxqzpu7hqtk93pkf7sw55rdv4k9z2vj050rxdr6za9ekfs3nlt5lr89jqpdmxsmlj9urqumg0h9wzpqecw7th56tdms40p2ny9q4ddvjsedzcplva53s```

* Signature is not recoverable. - results in panic
```lnbc2500u1pvjluezpp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqdq5xysxxatsyp3k7enxv4jsxqzpuaxtrnwngzn3kdzw5hydlzf03qdgm2hdq27cqv3agm2awhz5se903vruatfhq77w3ls4evs3ch9zw97j25emudupq63nyw24cg27h2rspk28uwq```
```
thread '<unnamed>' panicked at 'no other error may occur', rust-lightning/lightning-invoice/src/lib.rs:1062:23
stack backtrace:
   0:        0x1384da962 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b5b7de1c79b4b45
   1:        0x138267ffe - core::fmt::write::h65ec8c8a6aa7b549
   2:        0x1384da21a - std::io::Write::write_fmt::hc52e560ab9e57db4
   3:        0x1384d9d87 - std::panicking::default_hook::{{closure}}::h0974624c30a6e2b5
   4:        0x1384d8d3a - std::panicking::rust_panic_with_hook::h1cdaa4b48d8ea4a1
   5:        0x1384cffe7 - std::panicking::begin_panic::{{closure}}::h36f2c3c139495592
   6:        0x1384cffb2 - std::sys_common::backtrace::__rust_end_short_backtrace::hcd7d6a4a9bfbbba4
   7:        0x138577f4d - std::panicking::begin_panic::h778967c1427c2624
   8:        0x1384cc916 - lightning_invoice::Invoice::from_signed::hece781edd974c5de
   9:        0x138428dc8 - _Invoice_from_str
  10:        0x138561efa - _Java_org_ldk_impl_bindings_Invoice_1from_1str
```

**Comment by Synesso** [comment]
Replicated in latest, v0.0.100.1

**Comment by Synesso** [comment]
Is it easy to crack out a new release for this fix?

**Comment by TheBlueMatt** [comment]
Unless its a significant blocker, likely not - there's several important things blocking 0.0.101 that users have been asking for for a while.
