### ISSUE TITLE
This repo warns about binding being alpha but the lightningdevkit.org doesn't

### ISSUE THREAD

**Issue by Kixunil** [lightningdevkit/ldk-garbagecollected#70]
Randomly browsing this project, not sure if the warning in README still applies - if it does, I believe it should be repeated on https://lightningdevkit.org/tutorials/build_a_node_in_java/ so that people don't burn themselves. If it doesn't it should be removed from README.

**Comment by TheBlueMatt** [comment]
Thanks! Yep, that's just pretty stale.
